name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: yo.eki.do
      - uses: actions/checkout@v3
        with:
          repository: kissge/monolog
          path: monolog
      - uses: actions/setup-node@v3
        with:
          node-version: '18.3.0'
          cache: yarn
          cache-dependency-path: monolog/yarn.lock
      - run: yarn install --frozen-lockfile
        working-directory: monolog

      - name: Set up assets and configs
        run: |
          mv yo.eki.do/.env monolog/ &&
          mv yo.eki.do/images monolog/static/ &&
          mv yo.eki.do/static/* monolog/static/

      - run: yarn build
        working-directory: monolog

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: monolog/build
          CNAME: yo.eki.do
