name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - uses: actions/checkout@v2
        with:
          repository: kissge/monolog
          path: .monolog
      - run: mv config.ts .monolog/src/
      - run: mv images .monolog/static/
      - run: mv static/* .monolog/static/
      - run: mkdir .src && mv */ .src
      - run: yarn install
        working-directory: .monolog
      - run: yarn export
        working-directory: .monolog
      - run: head -c 100 .monolog/__sapper__/export/posts.json
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .monolog/__sapper__/export
          CNAME: yo.eki.do
